USE [master]
GO

/****** Object:  Database [BeerQuest]    Script Date: 21/02/2021 19:29:25 ******/
CREATE DATABASE [BeerQuest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BeerQuest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BeerQuest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BeerQuest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BeerQuest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BeerQuest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BeerQuest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BeerQuest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BeerQuest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BeerQuest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BeerQuest] SET ARITHABORT OFF 
GO

ALTER DATABASE [BeerQuest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BeerQuest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BeerQuest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BeerQuest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BeerQuest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BeerQuest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BeerQuest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BeerQuest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BeerQuest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BeerQuest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BeerQuest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BeerQuest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BeerQuest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BeerQuest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BeerQuest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BeerQuest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BeerQuest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BeerQuest] SET RECOVERY FULL 
GO

ALTER DATABASE [BeerQuest] SET  MULTI_USER 
GO

ALTER DATABASE [BeerQuest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BeerQuest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BeerQuest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BeerQuest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BeerQuest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BeerQuest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BeerQuest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BeerQuest] SET  READ_WRITE 
GO

